package com.lil4869.designpattern.proxy;

import com.lil4869.designpattern.bridge.Student;
import com.lil4869.designpattern.bridge.Teacher;
import com.lil4869.designpattern.entity.creature.Creature;

public class ProxyStudent implements Creature{
	Student student;

	@Override
	public void printDesc() {
	if(student ==null) {

		student=new Student("65536");
//		System.out.print("Generate ProxyStudent");
	}

	System.out.printf("A student generated by proxy pattern.");
		
	}

}
